apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dmygbh8kk-nodejs
  janus-idp.io/tekton: dmygbh8kk-nodejs
  backstage.io/kubernetes-id: dmygbh8kk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dmygbh8kk-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
