apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dmygbh8kk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dmygbh8kk-nodejs 
  name: dmygbh8kk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dmygbh8kk-nodejs 
